# Copy to terraform.tfvars and adjust. None of these are secrets - the
# actual SSH keys are generated by Terraform itself (see keys.tf), and AWS
# credentials come from the environment/IAM role, not from this file.

aws_region   = "ap-south-1"
cluster_name = "k8s-kubeadm"

vpc_cidr             = "10.0.0.0/16"
public_subnet_cidr   = "10.0.1.0/24"
private_subnet_cidr  = "10.0.2.0/24"
availability_zone    = "ap-south-1a"

# allowed_ssh_cidr is OPTIONAL - if left unset, Terraform auto-detects the
# public IP of whoever runs "terraform apply" and uses that. Only set this
# explicitly if you want to allow a DIFFERENT IP than the one running apply:
# allowed_ssh_cidr = "203.0.113.10/32"

bastion_instance_type = "t3.micro"
node_instance_type    = "t3.medium"
worker_count          = 2

kubernetes_version = "1.37.0-1.1"
pod_network_cidr   = "192.168.0.0/16"
